############################################################
#
# eureka 集群注册中心
# web访问端口号  约定：7001～3
#
############################################################
server:
  port: ${port:7001} # 动态传入
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-eureka-cluster

  redis:
    database: 0
    host: 1.15.44.134
    port: 6379
#    password: yuze123
eureka:
  instance:
    hostname: eureka-cluster-${server.port}
  other-node-port2: ${p2:7002}
  other-node-port3: ${p3:7003}
  client:
    # 取消自身注册
#    register-with-eureka: false
    # 不要获得服务列表
#    fetch-registry: false
    # 单实例配置自己的服务地址 高可用集群配置多个地址
    service-url:
      defaultZone: http://eureka-cluster-${eureka.other-node-port2}:${eureka.other-node-port2}/eureka/,http://eureka-cluster-${eureka.other-node-port3}:${eureka.other-node-port3}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000 # 清理无效节点时间

